# List of witch huts to watch out for
huts: []

# Bounding Box X size, default is 7
xSize: 7
# Bounding Box Z size, default is 9
zSize: 9
# Bounding Box height, default is 7
ySize: 7

# Bounding box starting Y level, default is 64
yStart: 64
