name: WitchHuts
version: '${version}'
main: me.lucthesloth.witchhuts.WitchHuts
api-version: 1.19
commands:
  reloadwitchhuts:
    description: Reloads the HuskPyramid config
    usage: /<command>
    permission: witchhuts.reload
    aliases: [reloadwh]