name: HuskPyramid
version: '${version}'
main: me.lucthesloth.domhusks.HuskPyramid
author: Lucthesloth
api-version: 1.19
commands:
  reloadhuskpyramid:
    description: Reloads the HuskPyramid config
    permission: huskpyramid.reload
    aliases: [reloadhp]