name: WitchHuts
version: '${version}'
main: me.lucthesloth.witchhuts.WitchHuts
author: LucTheSloth
api-version: 1.19
commands:
  reloadwitchhuts:
    permission: witchhuts.reload
    description: Reloads the HuskPyramid config
    aliases: [reloadwh]